"""
DStacks – two-player stacking game
===================================
Run  setup_assets.py  first to generate tiles, then:
    python main.py

Controls
--------
  ← / →         Move tile left / right
  Shift          Rotate tile 10°
  Space          Drop tile
  DROP button    Drop tile (mouse)
  ROTATE button  Rotate tile (mouse)
  M              Toggle music
  Enter          Restart after game over
"""

import pygame
import sys
import pymunk
import math
import random
import json
import os
import numpy as np
from scipy.spatial import ConvexHull

# ─── Pygame + display ────────────────────────────────────────────────────────

pygame.init()
pygame.mixer.init()

SCREEN_WIDTH  = 800
SCREEN_HEIGHT = 600
FPS           = 60
DEBUG         = True   # toggle with D key

screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
pygame.display.set_caption("DStacks")
clock = pygame.time.Clock()

# ─── Constants ────────────────────────────────────────────────────────────────

BAR_WIDTH          = 600
BAR_VISUAL_HEIGHT  = 8
BAR_PHYSICS_HEIGHT = 25
BAR_Y              = 500   # screen-Y of the top of the visible bar

GRAVITY            = -500
DAMPING            = 0.2
DENSITY            = 0.3
COLLISION_MARGIN   = 0.5
SOLVER_ITERATIONS  = 40
VELOCITY_THRESHOLD = 0.5
STILL_FRAMES       = 30
SETTLE_READY_DELAY = 10
SETTLE_DURATION    = 240
LOSS_TOLERANCE     = 5

ANGLE_STEP      = math.radians(10)
MOVE_STEP       = 8
TARGET_TILE_SIZE = 162     # max pixel dimension after scaling

# ─── Colours ──────────────────────────────────────────────────────────────────

P1_MAIN  = (231,  76,  60)
P1_LIGHT = (236, 112,  99)
P1_DARK  = (192,  57,  43)
P1_TINT  = (231,  76,  60,  40)

P2_MAIN  = ( 52, 152, 219)
P2_LIGHT = ( 93, 173, 226)
P2_DARK  = ( 41, 128, 185)
P2_TINT  = ( 52, 152, 219,  40)

NEUTRAL_BG_TOP    = (220, 220, 240)
NEUTRAL_BG_BOTTOM = (180, 180, 200)
BAR_COLOR         = (139,  69,  19)

# ─── Sound ────────────────────────────────────────────────────────────────────

sounds = {}
sound_enabled = True
try:
    sounds["drop"]      = pygame.mixer.Sound("assets/sounds/drop.wav")
    sounds["game_over"] = pygame.mixer.Sound("assets/sounds/game_over.wav")
    pygame.mixer.music.load("assets/sounds/background_music.ogg")
    pygame.mixer.music.set_volume(0.5)
    pygame.mixer.music.play(-1)
except Exception:
    sound_enabled = False

# ─── Tile loading ─────────────────────────────────────────────────────────────
#
#  FIX #1 (black backgrounds): try tiles_clean/ first (transparent PNGs
#  generated by setup_assets.py), fall back to tiles/ with runtime removal.
#
#  FIX #2 (Pymunk custom attributes): body_tile_registry maps  id(body) →
#  tile_data dict.  Pymunk's cffi Body may silently discard arbitrary attrs.

body_tile_registry: dict = {}   # id(body) → tile_data dict


def _remove_black_bg(surface: pygame.Surface) -> pygame.Surface:
    """Convert near-black pixels (brightness < 30) to transparent at runtime."""
    try:
        arr = pygame.surfarray.array3d(surface)   # shape (W, H, 3)
        brightness = arr[:, :, 0].astype(np.int32) + arr[:, :, 1] + arr[:, :, 2]
        alpha_arr  = np.where(brightness < 30, 0, 255).astype(np.uint8)
        result = surface.copy().convert_alpha()
        alpha_surf = pygame.surfarray.map_array(result, alpha_arr[:, :, np.newaxis].repeat(3, axis=2))
        pygame.surfarray.pixels_alpha(result)[:] = alpha_arr
        return result
    except Exception:
        return surface.convert_alpha()


def _load_tiles() -> list:
    """Return list of tile dicts, or [] on failure."""
    tile_defs = []

    json_path = "assets/data/tiles.json"
    if not os.path.exists(json_path):
        print(f"tiles.json not found at {json_path!r}. Run setup_assets.py first.")
        return tile_defs

    try:
        with open(json_path) as f:
            raw = json.load(f)
    except Exception as e:
        print(f"Could not parse {json_path}: {e}")
        return tile_defs

    print(f"tiles.json: {len(raw)} entries")

    for item in raw:
        fname = item["image_file"]

        # Prefer pre-processed transparent image; fall back to original with runtime removal
        clean_path = os.path.join("assets/images/tiles_clean", fname)
        orig_path  = os.path.join("assets/images/tiles",       fname)

        if os.path.exists(clean_path):
            img_path = clean_path
        elif os.path.exists(orig_path):
            img_path = orig_path
        else:
            print(f"  Warning: {fname} not found – skipping")
            continue

        try:
            img_orig = pygame.image.load(img_path).convert_alpha()
        except Exception as e:
            print(f"  Warning: could not load {img_path}: {e} – skipping")
            continue

        # If image came from original (black bg), strip it
        if img_path == orig_path:
            img_orig = _remove_black_bg(img_orig)

        orig_w, orig_h = img_orig.get_size()
        scale = min(TARGET_TILE_SIZE / orig_w, TARGET_TILE_SIZE / orig_h, 1.0)

        if scale < 1.0:
            new_w = int(orig_w * scale)
            new_h = int(orig_h * scale)
            img = pygame.transform.smoothscale(img_orig, (new_w, new_h))
        else:
            img   = img_orig
            scale = 1.0
            new_w, new_h = orig_w, orig_h

        pivot_key = "center_of_mass" if "center_of_mass" in item else "pivot"
        com = [item[pivot_key][0] * scale, item[pivot_key][1] * scale]

        convex_parts = [
            [[x * scale, y * scale] for x, y in part]
            for part in item["convex_parts"]
        ]

        outer_contour = (
            [[v[0] * scale, v[1] * scale] for v in item["outer_contour"]]
            if "outer_contour" in item else None
        )

        area = item.get("area")
        if area:
            area *= scale * scale

        tile_defs.append({
            "image_file":   fname,
            "surface":      img,
            "convex_parts": convex_parts,
            "com":          com,
            "area":         area,
            "outer_contour": outer_contour,
            "image_size":   (new_w, new_h),
        })
        print(f"  Loaded {fname} ({new_w}×{new_h})")

    print(f"Loaded {len(tile_defs)} tiles.")
    return tile_defs


tile_defs = _load_tiles()
use_images = len(tile_defs) > 0

# ─── Fallback polygon helper ──────────────────────────────────────────────────

def random_convex_polygon(avg_radius=45, num_verts=8):
    angles = sorted(random.uniform(0, 2 * math.pi) for _ in range(num_verts))
    pts    = [(avg_radius * random.uniform(0.7, 1.3) * math.cos(a),
               avg_radius * random.uniform(0.7, 1.3) * math.sin(a))
              for a in angles]
    hull   = ConvexHull(pts)
    return [pts[i] for i in hull.vertices]

# ─── Pymunk space ─────────────────────────────────────────────────────────────

space = pymunk.Space()
space.gravity            = (0, GRAVITY)
space.damping            = 1.0          # per-body damping set explicitly
space.collision_slop     = 0.2
space.iterations         = SOLVER_ITERATIONS

bar_body = pymunk.Body(body_type=pymunk.Body.STATIC)
bar_body.position = (
    SCREEN_WIDTH // 2,
    (SCREEN_HEIGHT - BAR_Y) - BAR_PHYSICS_HEIGHT / 2,
)
bar_shape = pymunk.Poly.create_box(bar_body, (BAR_WIDTH, BAR_PHYSICS_HEIGHT))
bar_shape.friction         = 1.0
bar_shape.elasticity       = 0.05
bar_shape.collision_margin = COLLISION_MARGIN
space.add(bar_body, bar_shape)

# ─── Coordinate helpers ───────────────────────────────────────────────────────

def to_pygame(p):
    """Convert Pymunk world coords → Pygame screen coords (Y flip)."""
    if hasattr(p, "x"):
        return int(p.x), int(SCREEN_HEIGHT - p.y)
    return int(p[0]), int(SCREEN_HEIGHT - p[1])

# ─── Drawing helpers ──────────────────────────────────────────────────────────

def draw_gradient_rect(surf, col_top, col_bot, rect):
    for y in range(rect.top, rect.bottom):
        t = (y - rect.top) / rect.height
        r = int(col_top[0] * (1 - t) + col_bot[0] * t)
        g = int(col_top[1] * (1 - t) + col_bot[1] * t)
        b = int(col_top[2] * (1 - t) + col_bot[2] * t)
        pygame.draw.line(surf, (r, g, b), (rect.left, y), (rect.right, y))


def draw_rounded_rect(surf, color, rect, radius, border=0, border_color=None):
    x, y, w, h = rect
    radius = min(radius, w // 2, h // 2)
    s = pygame.Surface((w, h), pygame.SRCALPHA)
    pygame.draw.rect(s, color, (0, 0, w, h), border_radius=radius)
    if border > 0 and border_color:
        pygame.draw.rect(s, border_color, (0, 0, w, h), border, border_radius=radius)
    surf.blit(s, (x, y))


def draw_background(player: int):
    draw_gradient_rect(screen, NEUTRAL_BG_TOP, NEUTRAL_BG_BOTTOM,
                       pygame.Rect(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT))
    tint = P1_TINT if player == 1 else P2_TINT
    overlay = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
    overlay.fill(tint)
    screen.blit(overlay, (0, 0))


# ─── FIX #3: correct COM-offset formula ──────────────────────────────────────
#
#  pygame.transform.rotate(img, +angle_deg) is CCW in screen space (pygame convention).
#  In screen Y-down coords CCW by θ maps (vx,vy) → (vx·cosθ+vy·sinθ, −vx·sinθ+vy·cosθ).
#  This is identical to Pymunk local_to_world→to_pygame, so image and physics stay welded.

def _rotated_com_offset(com, img_w, img_h, angle_rad):
    """
    Returns (rx, ry) – screen-space offset of the COM pixel from the centre
    of the rotated image returned by pygame.transform.rotate(img, +angle_deg).
    Formula: CCW rotation in Y-down screen space.
    """
    cx = img_w / 2
    cy = img_h / 2
    dx = com[0] - cx
    dy = com[1] - cy

    # CW rotation in screen space (Y-down)
    cos_a = math.cos(angle_rad)
    sin_a = math.sin(angle_rad)
    rx =  dx * cos_a + dy * sin_a
    ry = -dx * sin_a + dy * cos_a

    return rx, ry


def _blit_tile(surface, img, com, angle_rad, screen_pos):
    """Blit a rotated tile image so that the COM pixel lands on screen_pos."""
    angle_deg = math.degrees(angle_rad)
    rotated   = pygame.transform.rotate(img, angle_deg)   # +angle_deg: CCW matches physics Y-flip

    rx, ry = _rotated_com_offset(com, img.get_width(), img.get_height(), angle_rad)
    rot_cx = rotated.get_width()  / 2
    rot_cy = rotated.get_height() / 2

    draw_x = screen_pos[0] - (rot_cx + rx)
    draw_y = screen_pos[1] - (rot_cy + ry)
    surface.blit(rotated, (draw_x, draw_y))


# ─── Draw all physics objects ─────────────────────────────────────────────────

_drawn_ids: set = set()   # suppress repeated debug prints


def draw_objects():
    drawn_bodies = set()   # each body drawn only once (it has multiple shapes)
    for shape in space.shapes:
        if shape is bar_shape:
            continue
        if not isinstance(shape, pymunk.Poly):
            continue

        body = shape.body
        if id(body) in drawn_bodies:
            continue
        drawn_bodies.add(id(body))

        tile = body_tile_registry.get(id(body))

        if tile is not None:
            screen_pos = to_pygame(body.position)
            _blit_tile(screen, tile["surface"], tile["com"],
                       body.angle, screen_pos)

        else:
            # Fallback coloured polygon
            verts = [to_pygame(body.local_to_world(v)) for v in shape.get_vertices()]
            if len(verts) >= 3:
                player = getattr(body, "player", 0)
                color  = P1_MAIN if player == 1 else P2_MAIN if player == 2 else (180, 180, 180)
                pygame.draw.polygon(screen, color, verts)
                pygame.draw.polygon(screen, (0, 0, 0), verts, 2)


def draw_physics_outlines():
    """TRUTHFUL debug: reads vertices directly from Pymunk, no manual math.

    Cyan  = tile collision shapes (ACTUAL Pymunk geometry)
    Yellow = bar physics shape
    Red   = body centre-of-mass
    Press D to toggle.
    """
    # ── Bar (yellow) ─────────────────────────────────────────────────────────
    bar_world = [bar_body.local_to_world(v) for v in bar_shape.get_vertices()]
    bar_sv    = [to_pygame(v) for v in bar_world]
    if len(bar_sv) >= 3:
        pygame.draw.polygon(screen, (255, 230, 0), bar_sv, 3)

    # ── Tile shapes — deduplicate by body ────────────────────────────────────
    seen_bodies = set()
    for shape in space.shapes:
        if shape is bar_shape or not isinstance(shape, pymunk.Poly):
            continue
        body = shape.body

        # ── Cyan: actual Pymunk collision shapes (authoritative) ──────────
        world_verts = [body.local_to_world(v) for v in shape.get_vertices()]
        sv = [to_pygame(v) for v in world_verts]
        if len(sv) >= 3:
            pygame.draw.polygon(screen, (0, 230, 255), sv, 1)

        if id(body) in seen_bodies:
            continue
        seen_bodies.add(id(body))

        tile = body_tile_registry.get(id(body))
        com_s = to_pygame(body.position)

        # ── White: outer contour — image boundary with CORRECT rotation ──
        # Formula: for image-relative pixel (vx, vy) in Y-down space,
        # screen offset = (vx*cos + vy*sin,  -vx*sin + vy*cos)
        # This matches both Pymunk local_to_world→to_pygame AND rotate(img,+angle_deg).
        # If this white outline perfectly overlaps the image edge → fully welded.
        if tile and tile.get("outer_contour"):
            cos_a = math.cos(body.angle)
            sin_a = math.sin(body.angle)
            oc_sv = []
            for vx, vy in tile["outer_contour"]:   # image-relative Y-down
                dx =  vx * cos_a + vy * sin_a      # CW rotation (matches image)
                dy = -vx * sin_a + vy * cos_a
                oc_sv.append((int(com_s[0] + dx), int(com_s[1] + dy)))
            if len(oc_sv) >= 3:
                pygame.draw.polygon(screen, (255, 255, 255), oc_sv, 1)

        # ── Red: COM crosshair ────────────────────────────────────────────
        pygame.draw.circle(screen, (255, 50, 50), com_s, 4)
        pygame.draw.line(screen, (255,50,50), (com_s[0]-8,com_s[1]), (com_s[0]+8,com_s[1]), 1)
        pygame.draw.line(screen, (255,50,50), (com_s[0],com_s[1]-8), (com_s[0],com_s[1]+8), 1)

    # ── Legend ───────────────────────────────────────────────────────────────
    fnt = pygame.font.Font(None, 22)
    for i, (col, txt) in enumerate([
        ((0, 230, 255),  "CYAN  = physics shapes (Pymunk)"),
        ((255, 255, 255),"WHITE = image outline (must overlap CYAN)"),
        ((255, 230, 0),  "YELLOW= bar physics shape"),
        ((255,  50, 50), "RED   = centre of mass"),
        ((200, 200, 200),"[D]   = toggle debug overlay"),
    ]):
        screen.blit(fnt.render(txt, True, col), (8, 8 + i * 20))


def draw_preview(surface, pdata, x, y, angle, player):
    if "surface" in pdata:
        _blit_tile(surface, pdata["surface"], pdata["com"], angle, (x, y))
    else:
        # Fallback polygon preview
        ca, sa = math.cos(angle), math.sin(angle)
        pts = [(x + vx * ca - vy * sa, y - (vx * sa + vy * ca))
               for vx, vy in pdata["vertices"]]
        if len(pts) >= 3:
            color = P1_MAIN + (180,) if player == 1 else P2_MAIN + (180,)
            s = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
            pygame.draw.polygon(s, color, pts)
            surface.blit(s, (0, 0))
            pygame.draw.polygon(surface, (0, 0, 0), pts, 2)


# ─── Game-logic helpers ───────────────────────────────────────────────────────

def all_bodies_still():
    return all(
        b.velocity.length <= VELOCITY_THRESHOLD
        for b in space.bodies
        if b.body_type == pymunk.Body.DYNAMIC
    )


def check_loss(player):
    for body in space.bodies:
        if body.body_type != pymunk.Body.DYNAMIC:
            continue
        if getattr(body, "player", -1) != player:
            continue
        for shape in body.shapes:
            if not isinstance(shape, pymunk.Poly):
                continue
            screen_verts = [to_pygame(body.local_to_world(v))
                            for v in shape.get_vertices()]
            if screen_verts and max(v[1] for v in screen_verts) > BAR_Y + LOSS_TOLERANCE:
                return True
    return False


def _make_preview_data():
    if tile_defs:
        chosen = random.choice(tile_defs)
        return {
            "image_file":   chosen["image_file"],
            "surface":      chosen["surface"],
            "convex_parts": chosen["convex_parts"],
            "com":          chosen["com"],
            "area":         chosen.get("area"),
            "outer_contour": chosen.get("outer_contour"),
        }
    return {"vertices": random_convex_polygon()}


def drop_tile(pdata, x, y_screen, angle):
    """Create a physics body + shapes for the given preview_data. Returns body."""
    pos = (x, SCREEN_HEIGHT - y_screen)

    if "convex_parts" in pdata:
        parts = pdata["convex_parts"]
        area  = pdata.get("area") or sum(
            0.5 * abs(sum(parts[pi][i][0] * parts[pi][(i+1) % len(parts[pi])][1]
                          - parts[pi][(i+1) % len(parts[pi])][0] * parts[pi][i][1]
                          for i in range(len(parts[pi]))))
            for pi in range(len(parts))
        )
        mass   = max(0.1, area * DENSITY)
        all_v  = [(x, -y) for part in parts for x, y in part]  # Y-flip for moment
        moment = pymunk.moment_for_poly(mass, all_v) if all_v else float("inf")
        body   = pymunk.Body(mass, moment)
        body.position         = pos
        body.angle            = angle
        body.linear_damping   = DAMPING
        body.angular_damping  = DAMPING
        body.player           = current_player          # noqa: F821 – set before call

        # FIX #2: store in registry, not as body attribute
        body_tile_registry[id(body)] = pdata

        shapes = []
        for part in parts:
            sh = pymunk.Poly(body, [(x, -y) for x, y in part])  # Y-flip: image Y-down → Pymunk Y-up
            sh.friction         = 1.0
            sh.elasticity       = 0.05
            sh.collision_margin = COLLISION_MARGIN
            shapes.append(sh)
        space.add(body, *shapes)

    else:
        verts  = pdata["vertices"]
        mass   = 1.0
        moment = pymunk.moment_for_poly(mass, verts)
        body   = pymunk.Body(mass, moment)
        body.position        = pos
        body.angle           = angle
        body.linear_damping  = DAMPING
        body.angular_damping = DAMPING
        body.player          = current_player           # noqa: F821
        sh = pymunk.Poly(body, verts)
        sh.friction  = 1.0
        sh.elasticity = 0.05
        sh.collision_margin = COLLISION_MARGIN
        space.add(body, sh)

    if sound_enabled and "drop" in sounds:
        sounds["drop"].play()

    return body


def reset_game():
    """Remove all dynamic bodies and reset state (bar stays)."""
    to_remove_bodies = [b for b in space.bodies  if b.body_type == pymunk.Body.DYNAMIC]
    to_remove_shapes = [s for s in space.shapes  if s is not bar_shape]
    space.remove(*to_remove_bodies, *to_remove_shapes)
    body_tile_registry.clear()
    _drawn_ids.clear()


# ─── UI widgets ───────────────────────────────────────────────────────────────

try:
    btn_font = pygame.font.Font("assets/fonts/Roboto-Bold.ttf", 36)
except Exception:
    btn_font = pygame.font.Font(None, 42)

buttons = {
    "rotate": pygame.Rect(250, 540, 120, 50),
    "drop":   pygame.Rect(430, 540, 120, 50),
}
button_labels = {"rotate": "↻ ROTATE", "drop": "DROP"}

# ─── Game state ───────────────────────────────────────────────────────────────

current_player   = 1
game_over        = False
winner           = None
transition_active = False
transition_timer  = 0
next_player       = 1

preview_active = True
preview_data   = _make_preview_data()
preview_x      = SCREEN_WIDTH // 2
preview_y      = 50
preview_angle  = 0.0

dragging   = False
settling   = False
settle_frames      = 0
still_counter      = 0
settle_ready_ctr   = 0

key_left = key_right = key_shift = False
hover_button = None

# ─── Main loop ────────────────────────────────────────────────────────────────

running = True
while running:
    # ── Event handling ────────────────────────────────────────────────────────
    mouse_pos    = pygame.mouse.get_pos()
    hover_button = next((n for n, r in buttons.items() if r.collidepoint(mouse_pos)), None)

    for event in pygame.event.get():

        if event.type == pygame.QUIT:
            running = False

        # ── Keyboard ──────────────────────────────────────────────────────────
        if event.type == pygame.KEYDOWN:

            if event.key == pygame.K_d:
                DEBUG = not DEBUG
            if event.key == pygame.K_m:
                sound_enabled = not sound_enabled
                (pygame.mixer.music.unpause if sound_enabled else pygame.mixer.music.pause)()

            if event.key == pygame.K_RETURN and game_over:
                reset_game()
                current_player  = 1
                game_over       = False
                winner          = None
                transition_active = False
                preview_active  = True
                preview_data    = _make_preview_data()
                preview_x       = SCREEN_WIDTH // 2
                preview_angle   = 0.0
                settling        = False
                dragging        = False
                continue

            if not game_over and preview_active and not settling and not transition_active:
                if event.key == pygame.K_LEFT:
                    key_left = True
                elif event.key == pygame.K_RIGHT:
                    key_right = True
                elif event.key in (pygame.K_LSHIFT, pygame.K_RSHIFT):
                    key_shift = True
                elif event.key == pygame.K_SPACE:
                    body = drop_tile(preview_data, preview_x, preview_y, preview_angle)
                    preview_active = False
                    settling       = True
                    settle_frames  = still_counter = settle_ready_ctr = 0

        if event.type == pygame.KEYUP:
            if event.key == pygame.K_LEFT:          key_left  = False
            elif event.key == pygame.K_RIGHT:       key_right = False
            elif event.key in (pygame.K_LSHIFT, pygame.K_RSHIFT): key_shift = False

        # ── Mouse ─────────────────────────────────────────────────────────────
        if event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
            if settling or transition_active or game_over:
                continue

            clicked_button = None
            for name, rect in buttons.items():
                if rect.collidepoint(event.pos):
                    clicked_button = name
                    break

            if clicked_button == "rotate":
                preview_angle += ANGLE_STEP
            elif clicked_button == "drop":
                body = drop_tile(preview_data, preview_x, preview_y, preview_angle)
                preview_active = False
                settling       = True
                settle_frames  = still_counter = settle_ready_ctr = 0
            elif preview_active and not settling:
                dragging  = True
                preview_x = event.pos[0]

        if event.type == pygame.MOUSEBUTTONUP and event.button == 1:
            dragging = False

        if event.type == pygame.MOUSEMOTION:
            if dragging and preview_active and not settling and not transition_active and not game_over:
                preview_x = event.pos[0]

    # ── Continuous key movement ───────────────────────────────────────────────
    if not game_over and preview_active and not settling and not transition_active:
        if key_left:   preview_x -= MOVE_STEP
        if key_right:  preview_x += MOVE_STEP
        if key_shift:  preview_angle += ANGLE_STEP

    preview_x = max(20, min(SCREEN_WIDTH - 20, preview_x))

    # ── Physics step (sub-stepped for stability) ──────────────────────────────
    for _ in range(8):
        space.step(1 / FPS / 8)

    # ── Settle detection ──────────────────────────────────────────────────────
    if settling:
        settle_frames += 1
        if all_bodies_still():
            still_counter += 1
        else:
            still_counter = settle_ready_ctr = 0

        resolved = False
        if still_counter >= STILL_FRAMES:
            settle_ready_ctr += 1
            if settle_ready_ctr >= SETTLE_READY_DELAY:
                resolved = True
        elif settle_frames >= SETTLE_DURATION:
            resolved = True

        if resolved:
            settling = False
            if check_loss(current_player):
                game_over = True
                winner    = 3 - current_player
                if sound_enabled and "game_over" in sounds:
                    sounds["game_over"].play()
            else:
                transition_active = True
                transition_timer  = 60
                next_player       = 2 if current_player == 1 else 1

    # ── Player transition ─────────────────────────────────────────────────────
    if transition_active:
        transition_timer -= 1
        if transition_timer <= 0:
            transition_active = False
            current_player    = next_player
            preview_active    = True
            preview_data      = _make_preview_data()
            preview_x         = SCREEN_WIDTH // 2
            preview_angle     = 0.0
            dragging          = False
            key_left = key_right = key_shift = False

    # ── Drawing ───────────────────────────────────────────────────────────────
    active_p = next_player if transition_active else current_player
    draw_background(winner if game_over else active_p)

    # Bar
    bar_rect = pygame.Rect(
        SCREEN_WIDTH // 2 - BAR_WIDTH // 2, BAR_Y, BAR_WIDTH, BAR_VISUAL_HEIGHT
    )
    pygame.draw.rect(screen, BAR_COLOR, bar_rect, border_radius=5)
    pygame.draw.rect(screen, (0, 0, 0), bar_rect, 2, border_radius=5)

    draw_objects()
    if DEBUG:
        draw_physics_outlines()

    # Buttons
    for name, rect in buttons.items():
        p1c, p2c = P1_MAIN, P2_MAIN
        main_c  = P1_MAIN  if active_p == 1 else P2_MAIN
        light_c = P1_LIGHT if active_p == 1 else P2_LIGHT
        dark_c  = P1_DARK  if active_p == 1 else P2_DARK

        fill   = light_c if (hover_button == name and not game_over and not settling and not transition_active) else main_c
        draw_rounded_rect(screen, fill, rect, 12, border=2, border_color=dark_c)
        label  = btn_font.render(button_labels[name], True, (255, 255, 255))
        screen.blit(label, label.get_rect(center=rect.center))

    # Preview
    if preview_active and not settling and not transition_active and not game_over:
        draw_preview(screen, preview_data, preview_x, preview_y, preview_angle, current_player)

    # Transition overlay
    if transition_active:
        ov = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
        ov.fill((0, 0, 0, 100))
        screen.blit(ov, (0, 0))
        f72 = pygame.font.Font(None, 72)
        f48 = pygame.font.Font(None, 48)
        t = f72.render(f"{'Red' if next_player==1 else 'Blue'}'s Turn", True, (255, 255, 255))
        screen.blit(t, t.get_rect(center=(SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2 - 30)))
        s = f48.render("Get Ready...", True, (220, 220, 220))
        screen.blit(s, s.get_rect(center=(SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2 + 20)))

    # Game-over overlay
    if game_over:
        ov = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
        ov.fill((0, 0, 0, 150))
        screen.blit(ov, (0, 0))
        f72 = pygame.font.Font(None, 72)
        f48 = pygame.font.Font(None, 48)
        t = f72.render(f"{'Red' if winner==1 else 'Blue'} Wins!", True, (255, 255, 255))
        screen.blit(t, t.get_rect(center=(SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2 - 30)))
        s = f48.render("Press ENTER to restart", True, (220, 220, 220))
        screen.blit(s, s.get_rect(center=(SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2 + 20)))

    pygame.display.flip()
    clock.tick(FPS)

pygame.quit()
sys.exit()
