"""
DStacks – two-player stacking game
===================================
Run  setup_assets.py  first to generate tiles, then:
    python main.py

Controls
--------
  ← / →         Move tile left / right
  Shift          Rotate tile 10°
  Space          Drop tile
  DROP button    Drop tile (mouse)
  ROTATE button  Rotate tile (mouse)
  M              Toggle music
  Enter          Restart after game over
"""

import pygame
import sys
import pymunk
import math
import random
import json
import os
import numpy as np
from scipy.spatial import ConvexHull

# ─── Pygame + display ────────────────────────────────────────────────────────

pygame.init()
pygame.mixer.init()

SCREEN_WIDTH  = 800
SCREEN_HEIGHT = 600
FPS           = 60
DEBUG         = False  # toggle with D key to show collision outlines

screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
pygame.display.set_caption("DStacks")
clock = pygame.time.Clock()

# ─── Constants ────────────────────────────────────────────────────────────────

BAR_WIDTH          = 600
BAR_PHYSICS_HEIGHT = 14    # one value, used for both visual and physics
BAR_VISUAL_HEIGHT  = BAR_PHYSICS_HEIGHT   # visual = physics → no mismatch
BAR_Y              = 500   # screen-Y of the TOP surface of the bar (where tiles land)

GRAVITY            = -600          # slightly gentler fall
DAMPING            = 0.85          # global space damping — kills residual motion fast
DENSITY            = 0.3
COLLISION_MARGIN   = 0.0           # 0 = shapes touch exactly; >0 adds invisible padding that causes jitter
SOLVER_ITERATIONS  = 60            # more iterations = stiffer, more accurate contacts

# Stability detection — all three must hold simultaneously
VELOCITY_THRESHOLD   = 0.4         # linear speed px/s
ANGULAR_THRESHOLD    = 0.04        # radians/s  (catches spinning-but-not-translating tiles)
STILL_FRAMES         = 90          # frames (1.5 s) all bodies must be below both thresholds
SETTLE_READY_DELAY   = 6
SETTLE_DURATION      = 400         # hard timeout frames

LOSS_TOLERANCE     = 8

ANGLE_STEP      = math.radians(10)
MOVE_STEP       = 8
TARGET_TILE_SIZE = 130    # silhouette target — all characters same game size

# ─── Camera / scroll ──────────────────────────────────────────────────────────
# Camera only advances between turns (never while a tile is falling).
# Target: keep the highest SETTLED tile at the vertical centre of the screen.
CAMERA_LERP_RATE  = 0.03   # slow, smooth scroll between turns

# ─── Level / bar-growth ───────────────────────────────────────────────────────
LEVEL_TILES         = 10    # successful tiles before bar grows
BAR_GROWTH_FACTOR   = 1.20  # bar gets 20 % wider per level
MAX_BAR_WIDTH       = SCREEN_WIDTH - 20   # cap so bar can't exceed screen

# ─── Colours ──────────────────────────────────────────────────────────────────

P1_MAIN  = (220,  60,  50)
P1_LIGHT = (240, 100,  88)
P1_DARK  = (170,  35,  25)
P1_TINT  = (220,  60,  50,  25)

P2_MAIN  = ( 40, 130, 210)
P2_LIGHT = ( 80, 165, 235)
P2_DARK  = ( 25,  95, 165)
P2_TINT  = ( 40, 130, 210,  25)

NEUTRAL_BG_TOP    = (235, 238, 250)
NEUTRAL_BG_BOTTOM = (195, 200, 222)
BAR_COLOR         = ( 90,  55,  20)   # darker walnut brown
BAR_SHADOW        = ( 55,  32,  10)

# ─── Sound ────────────────────────────────────────────────────────────────────

sounds = {}
sound_enabled = True
try:
    sounds["drop"]      = pygame.mixer.Sound("assets/sounds/drop.wav")
    sounds["game_over"] = pygame.mixer.Sound("assets/sounds/game_over.wav")
    pygame.mixer.music.load("assets/sounds/background_music.ogg")
    pygame.mixer.music.set_volume(0.5)
    pygame.mixer.music.play(-1)
except Exception:
    sound_enabled = False

# ─── Tile loading ─────────────────────────────────────────────────────────────
#
#  FIX #1 (black backgrounds): try tiles_clean/ first (transparent PNGs
#  generated by setup_assets.py), fall back to tiles/ with runtime removal.
#
#  FIX #2 (Pymunk custom attributes): body_tile_registry maps  id(body) →
#  tile_data dict.  Pymunk's cffi Body may silently discard arbitrary attrs.

body_tile_registry: dict = {}   # id(body) → tile_data dict


def _remove_black_bg(surface: pygame.Surface) -> pygame.Surface:
    """Convert near-black pixels (brightness < 30) to transparent at runtime."""
    try:
        arr = pygame.surfarray.array3d(surface)   # shape (W, H, 3)
        brightness = arr[:, :, 0].astype(np.int32) + arr[:, :, 1] + arr[:, :, 2]
        alpha_arr  = np.where(brightness < 30, 0, 255).astype(np.uint8)
        result = surface.copy().convert_alpha()
        alpha_surf = pygame.surfarray.map_array(result, alpha_arr[:, :, np.newaxis].repeat(3, axis=2))
        pygame.surfarray.pixels_alpha(result)[:] = alpha_arr
        return result
    except Exception:
        return surface.convert_alpha()


def _load_tiles() -> list:
    """Return list of tile dicts, or [] on failure."""
    tile_defs = []

    json_path = "assets/data/tiles.json"
    if not os.path.exists(json_path):
        print(f"tiles.json not found at {json_path!r}. Run setup_assets.py first.")
        return tile_defs

    try:
        with open(json_path) as f:
            raw = json.load(f)
    except Exception as e:
        print(f"Could not parse {json_path}: {e}")
        return tile_defs

    print(f"tiles.json: {len(raw)} entries")

    for item in raw:
        fname = item["image_file"]

        # Prefer pre-processed transparent image; fall back to original with runtime removal
        clean_path = os.path.join("assets/images/tiles_clean", fname)
        orig_path  = os.path.join("assets/images/tiles",       fname)

        if os.path.exists(clean_path):
            img_path = clean_path
        elif os.path.exists(orig_path):
            img_path = orig_path
        else:
            print(f"  Warning: {fname} not found – skipping")
            continue

        try:
            img_orig = pygame.image.load(img_path).convert_alpha()
        except Exception as e:
            print(f"  Warning: could not load {img_path}: {e} – skipping")
            continue

        # If image came from original (black bg), strip it
        if img_path == orig_path:
            img_orig = _remove_black_bg(img_orig)

        orig_w, orig_h = img_orig.get_size()

        # Scale by SILHOUETTE extent (from outer_contour) so every character
        # occupies the same in-game footprint regardless of image padding.
        if "outer_contour" in item and item["outer_contour"]:
            oc = item["outer_contour"]
            sil_w = max(v[0] for v in oc) - min(v[0] for v in oc)
            sil_h = max(v[1] for v in oc) - min(v[1] for v in oc)
            sil_extent = max(sil_w, sil_h)
        else:
            sil_extent = max(orig_w, orig_h)

        scale = min(TARGET_TILE_SIZE / sil_extent, 1.0) if sil_extent > 0 else 1.0
        new_w = int(orig_w * scale)
        new_h = int(orig_h * scale)
        img   = pygame.transform.smoothscale(img_orig, (new_w, new_h)) if scale < 1.0 else img_orig
        if scale >= 1.0:
            new_w, new_h = orig_w, orig_h

        pivot_key = "center_of_mass" if "center_of_mass" in item else "pivot"
        com = [item[pivot_key][0] * scale, item[pivot_key][1] * scale]

        convex_parts = [
            [[x * scale, y * scale] for x, y in part]
            for part in item["convex_parts"]
        ]

        outer_contour = (
            [[v[0] * scale, v[1] * scale] for v in item["outer_contour"]]
            if "outer_contour" in item else None
        )

        area = item.get("area")
        if area:
            area *= scale * scale

        tile_defs.append({
            "image_file":   fname,
            "surface":      img,
            "convex_parts": convex_parts,
            "com":          com,
            "area":         area,
            "outer_contour": outer_contour,
            "image_size":   (new_w, new_h),
        })
        print(f"  Loaded {fname} ({new_w}×{new_h})")

    print(f"Loaded {len(tile_defs)} tiles.")
    return tile_defs


tile_defs = _load_tiles()
use_images = len(tile_defs) > 0

# ─── Fallback polygon helper ──────────────────────────────────────────────────

def random_convex_polygon(avg_radius=45, num_verts=8):
    angles = sorted(random.uniform(0, 2 * math.pi) for _ in range(num_verts))
    pts    = [(avg_radius * random.uniform(0.7, 1.3) * math.cos(a),
               avg_radius * random.uniform(0.7, 1.3) * math.sin(a))
              for a in angles]
    hull   = ConvexHull(pts)
    return [pts[i] for i in hull.vertices]

# ─── Pymunk space ─────────────────────────────────────────────────────────────

space = pymunk.Space()
space.gravity            = (0, GRAVITY)
space.damping            = DAMPING     # applied every step — drains energy continuously
space.collision_slop     = 0.1        # tighter overlap tolerance
space.iterations         = SOLVER_ITERATIONS

bar_body = pymunk.Body(body_type=pymunk.Body.STATIC)
# BAR_Y is screen-Y of the bar's TOP surface (camera_y=0 at game start).
# world_y of top surface  = SCREEN_HEIGHT - BAR_Y
# body centre sits half a bar-height below that:
bar_world_y = (SCREEN_HEIGHT - BAR_Y) - BAR_PHYSICS_HEIGHT / 2
bar_body.position = (SCREEN_WIDTH // 2, bar_world_y)
bar_shape = pymunk.Poly.create_box(bar_body, (BAR_WIDTH, BAR_PHYSICS_HEIGHT))
bar_shape.friction         = 1.5
bar_shape.elasticity       = 0.0    # completely dead stop on bar
bar_shape.collision_margin = 0.0
space.add(bar_body, bar_shape)

# ─── Camera state (global so to_pygame can use it) ───────────────────────────
camera_y = 0.0   # world units the camera has scrolled upward

# ─── Coordinate helpers ───────────────────────────────────────────────────────

def to_pygame(p):
    """Convert Pymunk world coords → Pygame screen coords (Y flip + camera)."""
    px = p.x if hasattr(p, "x") else p[0]
    py = p.y if hasattr(p, "y") else p[1]
    return int(px), int(SCREEN_HEIGHT - py + camera_y)

# ─── Drawing helpers ──────────────────────────────────────────────────────────

def draw_gradient_rect(surf, col_top, col_bot, rect):
    for y in range(rect.top, rect.bottom):
        t = (y - rect.top) / rect.height
        r = int(col_top[0] * (1 - t) + col_bot[0] * t)
        g = int(col_top[1] * (1 - t) + col_bot[1] * t)
        b = int(col_top[2] * (1 - t) + col_bot[2] * t)
        pygame.draw.line(surf, (r, g, b), (rect.left, y), (rect.right, y))


def draw_rounded_rect(surf, color, rect, radius, border=0, border_color=None):
    x, y, w, h = rect
    radius = min(radius, w // 2, h // 2)
    s = pygame.Surface((w, h), pygame.SRCALPHA)
    pygame.draw.rect(s, color, (0, 0, w, h), border_radius=radius)
    if border > 0 and border_color:
        pygame.draw.rect(s, border_color, (0, 0, w, h), border, border_radius=radius)
    surf.blit(s, (x, y))


def draw_background(player: int):
    # Base gradient
    draw_gradient_rect(screen, NEUTRAL_BG_TOP, NEUTRAL_BG_BOTTOM,
                       pygame.Rect(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT))

    # Subtle dot-grid for depth (every 32px)
    dot_surf = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
    for gx in range(0, SCREEN_WIDTH, 32):
        for gy in range(0, SCREEN_HEIGHT, 32):
            pygame.draw.circle(dot_surf, (160, 165, 190, 40), (gx, gy), 1)
    screen.blit(dot_surf, (0, 0))

    # Player colour tint — stronger at bottom (where action is)
    tint_col = P1_MAIN if player == 1 else P2_MAIN
    tint_surf = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
    for y in range(SCREEN_HEIGHT):
        alpha = int(18 * (y / SCREEN_HEIGHT))   # 0 at top, 18 at bottom
        pygame.draw.line(tint_surf, (*tint_col, alpha), (0, y), (SCREEN_WIDTH, y))
    screen.blit(tint_surf, (0, 0))


# ─── FIX #3: correct COM-offset formula ──────────────────────────────────────
#
#  pygame.transform.rotate(img, +angle_deg) is CCW in screen space (pygame convention).
#  In screen Y-down coords CCW by θ maps (vx,vy) → (vx·cosθ+vy·sinθ, −vx·sinθ+vy·cosθ).
#  This is identical to Pymunk local_to_world→to_pygame, so image and physics stay welded.

def _rotated_com_offset(com, img_w, img_h, angle_rad):
    """
    Returns (rx, ry) – screen-space offset of the COM pixel from the centre
    of the rotated image returned by pygame.transform.rotate(img, +angle_deg).
    Formula: CCW rotation in Y-down screen space.
    """
    cx = img_w / 2
    cy = img_h / 2
    dx = com[0] - cx
    dy = com[1] - cy

    # CW rotation in screen space (Y-down)
    cos_a = math.cos(angle_rad)
    sin_a = math.sin(angle_rad)
    rx =  dx * cos_a + dy * sin_a
    ry = -dx * sin_a + dy * cos_a

    return rx, ry


def _blit_tile(surface, img, com, angle_rad, screen_pos):
    """Blit a rotated tile image so that the COM pixel lands on screen_pos."""
    angle_deg = math.degrees(angle_rad)
    rotated   = pygame.transform.rotate(img, angle_deg)   # +angle_deg: CCW matches physics Y-flip

    rx, ry = _rotated_com_offset(com, img.get_width(), img.get_height(), angle_rad)
    rot_cx = rotated.get_width()  / 2
    rot_cy = rotated.get_height() / 2

    draw_x = screen_pos[0] - (rot_cx + rx)
    draw_y = screen_pos[1] - (rot_cy + ry)
    surface.blit(rotated, (draw_x, draw_y))


# ─── Draw all physics objects ─────────────────────────────────────────────────

_drawn_ids: set = set()   # suppress repeated debug prints


def draw_objects():
    drawn_bodies = set()   # each body drawn only once (it has multiple shapes)
    for shape in space.shapes:
        if shape is bar_shape:
            continue
        if not isinstance(shape, pymunk.Poly):
            continue

        body = shape.body
        if id(body) in drawn_bodies:
            continue
        drawn_bodies.add(id(body))

        tile = body_tile_registry.get(id(body))

        if tile is not None:
            screen_pos = to_pygame(body.position)
            _blit_tile(screen, tile["surface"], tile["com"],
                       body.angle, screen_pos)

        else:
            # Fallback coloured polygon
            verts = [to_pygame(body.local_to_world(v)) for v in shape.get_vertices()]
            if len(verts) >= 3:
                player = getattr(body, "player", 0)
                color  = P1_MAIN if player == 1 else P2_MAIN if player == 2 else (180, 180, 180)
                pygame.draw.polygon(screen, color, verts)
                pygame.draw.polygon(screen, (0, 0, 0), verts, 2)


def draw_physics_outlines():
    """TRUTHFUL debug: reads vertices directly from Pymunk, no manual math.

    Cyan  = tile collision shapes (ACTUAL Pymunk geometry)
    Yellow = bar physics shape
    Red   = body centre-of-mass
    Press D to toggle.
    """
    # ── Bar (yellow) ─────────────────────────────────────────────────────────
    bar_world = [bar_body.local_to_world(v) for v in bar_shape.get_vertices()]
    bar_sv    = [to_pygame(v) for v in bar_world]
    if len(bar_sv) >= 3:
        pygame.draw.polygon(screen, (255, 230, 0), bar_sv, 3)

    # ── Tile shapes — deduplicate by body ────────────────────────────────────
    seen_bodies = set()
    for shape in space.shapes:
        if shape is bar_shape or not isinstance(shape, pymunk.Poly):
            continue
        body = shape.body

        # ── Cyan: actual Pymunk collision shapes (authoritative) ──────────
        world_verts = [body.local_to_world(v) for v in shape.get_vertices()]
        sv = [to_pygame(v) for v in world_verts]
        if len(sv) >= 3:
            pygame.draw.polygon(screen, (0, 230, 255), sv, 1)

        if id(body) in seen_bodies:
            continue
        seen_bodies.add(id(body))

        tile = body_tile_registry.get(id(body))
        com_s = to_pygame(body.position)

        # ── White: outer contour — image boundary with CORRECT rotation ──
        # Formula: for image-relative pixel (vx, vy) in Y-down space,
        # screen offset = (vx*cos + vy*sin,  -vx*sin + vy*cos)
        # This matches both Pymunk local_to_world→to_pygame AND rotate(img,+angle_deg).
        # If this white outline perfectly overlaps the image edge → fully welded.
        if tile and tile.get("outer_contour"):
            cos_a = math.cos(body.angle)
            sin_a = math.sin(body.angle)
            oc_sv = []
            for vx, vy in tile["outer_contour"]:   # image-relative Y-down
                dx =  vx * cos_a + vy * sin_a      # CW rotation (matches image)
                dy = -vx * sin_a + vy * cos_a
                oc_sv.append((int(com_s[0] + dx), int(com_s[1] + dy)))
            if len(oc_sv) >= 3:
                pygame.draw.polygon(screen, (255, 255, 255), oc_sv, 1)

        # ── Red: COM crosshair ────────────────────────────────────────────
        pygame.draw.circle(screen, (255, 50, 50), com_s, 4)
        pygame.draw.line(screen, (255,50,50), (com_s[0]-8,com_s[1]), (com_s[0]+8,com_s[1]), 1)
        pygame.draw.line(screen, (255,50,50), (com_s[0],com_s[1]-8), (com_s[0],com_s[1]+8), 1)

    # ── Legend ───────────────────────────────────────────────────────────────
    fnt = pygame.font.Font(None, 22)
    for i, (col, txt) in enumerate([
        ((0, 230, 255),  "CYAN  = physics shapes (Pymunk)"),
        ((255, 255, 255),"WHITE = image outline (must overlap CYAN)"),
        ((255, 230, 0),  "YELLOW= bar physics shape"),
        ((255,  50, 50), "RED   = centre of mass"),
        ((200, 200, 200),"[D]   = toggle debug overlay"),
    ]):
        screen.blit(fnt.render(txt, True, col), (8, 8 + i * 20))


def draw_preview(surface, pdata, x, y, angle, player):
    if "surface" in pdata:
        _blit_tile(surface, pdata["surface"], pdata["com"], angle, (x, y))
    else:
        # Fallback polygon preview
        ca, sa = math.cos(angle), math.sin(angle)
        pts = [(x + vx * ca - vy * sa, y - (vx * sa + vy * ca))
               for vx, vy in pdata["vertices"]]
        if len(pts) >= 3:
            color = P1_MAIN + (180,) if player == 1 else P2_MAIN + (180,)
            s = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
            pygame.draw.polygon(s, color, pts)
            surface.blit(s, (0, 0))
            pygame.draw.polygon(surface, (0, 0, 0), pts, 2)


# ─── Game-logic helpers ───────────────────────────────────────────────────────

def all_bodies_still():
    """True only when every dynamic body is below BOTH linear and angular thresholds.
    Checking angular_velocity catches tiles that are spinning in place (low linear
    speed but still rocking/vibrating on the pile)."""
    for b in space.bodies:
        if b.body_type != pymunk.Body.DYNAMIC:
            continue
        if b.velocity.length > VELOCITY_THRESHOLD:
            return False
        if abs(b.angular_velocity) > ANGULAR_THRESHOLD:
            return False
    return True


def check_loss(player):
    """A tile is 'lost' only when its centre of mass is below the bar's
    bottom surface — i.e. it has fully cleared the bar and is falling away.
    Tiles resting ON the bar will never trigger this."""
    bar_bottom_world = bar_body.position.y - BAR_PHYSICS_HEIGHT / 2
    for body in space.bodies:
        if body.body_type != pymunk.Body.DYNAMIC:
            continue
        if getattr(body, "player", -1) != player:
            continue
        # body.position.y is the COM in world Y (Y-up).
        # Below bar bottom + a small margin = truly fallen off.
        if body.position.y < bar_bottom_world - LOSS_TOLERANCE:
            return True
    return False


def fallen_tile_off_screen(player):
    """Return True once every fallen tile belonging to player is fully
    below the visible screen (so game-over is declared only after the
    tile disappears from view, not the instant it leaves the bar)."""
    bar_bottom_world = bar_body.position.y - BAR_PHYSICS_HEIGHT / 2
    for body in space.bodies:
        if body.body_type != pymunk.Body.DYNAMIC:
            continue
        if getattr(body, "player", -1) != player:
            continue
        if body.position.y >= bar_bottom_world - LOSS_TOLERANCE:
            continue   # this tile is still on the bar — ignore it
        # Find the highest vertex of this body in screen coords
        max_world_y = body.position.y   # fallback
        for shape in body.shapes:
            if isinstance(shape, pymunk.Poly):
                for v in shape.get_vertices():
                    wv = body.local_to_world(v)
                    if wv.y > max_world_y:
                        max_world_y = wv.y
        screen_top = SCREEN_HEIGHT - max_world_y + camera_y
        if screen_top <= SCREEN_HEIGHT:
            return False   # at least one fallen tile still visible
    return True   # all fallen tiles are off screen


def _make_preview_data():
    if tile_defs:
        chosen = random.choice(tile_defs)
        return {
            "image_file":   chosen["image_file"],
            "surface":      chosen["surface"],
            "convex_parts": chosen["convex_parts"],
            "com":          chosen["com"],
            "area":         chosen.get("area"),
            "outer_contour": chosen.get("outer_contour"),
        }
    return {"vertices": random_convex_polygon()}


def drop_tile(pdata, x, y_screen, angle):
    """Create a physics body + shapes for the given preview_data. Returns body."""
    # y_screen is screen-pixels from top; convert to world Y accounting for camera
    world_y = SCREEN_HEIGHT - y_screen + camera_y

    pos = (x, world_y)

    if "convex_parts" in pdata:
        parts = pdata["convex_parts"]
        area  = pdata.get("area") or sum(
            0.5 * abs(sum(parts[pi][i][0] * parts[pi][(i+1) % len(parts[pi])][1]
                          - parts[pi][(i+1) % len(parts[pi])][0] * parts[pi][i][1]
                          for i in range(len(parts[pi]))))
            for pi in range(len(parts))
        )
        mass   = max(0.1, area * DENSITY)
        all_v  = [(x, -y) for part in parts for x, y in part]  # Y-flip for moment
        moment = pymunk.moment_for_poly(mass, all_v) if all_v else float("inf")
        body   = pymunk.Body(mass, moment)
        body.position         = pos
        body.angle            = angle
        body.player           = current_player          # noqa: F821 – set before call

        # FIX #2: store in registry, not as body attribute
        body_tile_registry[id(body)] = pdata

        shapes = []
        for part in parts:
            sh = pymunk.Poly(body, [(x, -y) for x, y in part])
            sh.friction         = 1.2
            sh.elasticity       = 0.0   # no bounce whatsoever
            sh.collision_margin = 0.0   # exact shape — margin causes jitter
            shapes.append(sh)
        space.add(body, *shapes)

    else:
        verts  = pdata["vertices"]
        mass   = 1.0
        moment = pymunk.moment_for_poly(mass, verts)
        body   = pymunk.Body(mass, moment)
        body.position        = pos
        body.angle           = angle
        body.player          = current_player           # noqa: F821
        sh = pymunk.Poly(body, verts)
        sh.friction         = 1.2
        sh.elasticity       = 0.0
        sh.collision_margin = 0.0
        space.add(body, sh)

    if sound_enabled and "drop" in sounds:
        sounds["drop"].play()

    return body


def _rebuild_bar(new_width):
    """Replace the static bar shape with one of new_width. Bar centre stays fixed."""
    global bar_shape, current_bar_width
    space.remove(bar_shape)
    current_bar_width = int(new_width)
    bar_shape = pymunk.Poly.create_box(bar_body, (current_bar_width, BAR_PHYSICS_HEIGHT))
    bar_shape.friction         = 1.0
    bar_shape.elasticity       = 0.05
    bar_shape.collision_margin = COLLISION_MARGIN
    space.add(bar_shape)


def reset_game():
    """Remove all dynamic bodies and reset state (bar stays)."""
    global camera_y, tiles_placed, current_level, current_bar_width, level_flash_timer, watching_fall
    to_remove_bodies = [b for b in space.bodies  if b.body_type == pymunk.Body.DYNAMIC]
    to_remove_shapes = [s for s in space.shapes  if s is not bar_shape]
    space.remove(*to_remove_bodies, *to_remove_shapes)
    body_tile_registry.clear()
    _drawn_ids.clear()
    camera_y          = 0.0
    tiles_placed      = 0
    current_level     = 1
    current_bar_width = BAR_WIDTH
    level_flash_timer = 0
    watching_fall     = False
    # Restore bar to original width
    _rebuild_bar(BAR_WIDTH)


# ─── UI widgets ───────────────────────────────────────────────────────────────

try:
    btn_font = pygame.font.Font("assets/fonts/Roboto-Bold.ttf", 36)
except Exception:
    btn_font = pygame.font.Font(None, 42)

buttons = {
    "rotate": pygame.Rect(SCREEN_WIDTH // 2 - 160, SCREEN_HEIGHT - 58, 140, 44),
    "drop":   pygame.Rect(SCREEN_WIDTH // 2 +  20, SCREEN_HEIGHT - 58, 140, 44),
}
button_labels = {"rotate": "↻  ROTATE", "drop": "▼  DROP"}

# ─── Game state ───────────────────────────────────────────────────────────────

current_player   = 1
game_over        = False
winner           = None
transition_active = False
transition_timer  = 0
next_player       = 1

# ─── Progression state ────────────────────────────────────────────────────────
tiles_placed      = 0          # total successful tiles this game
current_level     = 1
current_bar_width = BAR_WIDTH
level_flash_timer = 0          # frames left to show "Level Up!" banner

preview_active = True
preview_data   = _make_preview_data()
preview_x      = SCREEN_WIDTH // 2
preview_y      = 50
preview_angle  = 0.0

dragging      = False
settling      = False
watching_fall = False   # True while waiting for fallen tile to leave screen
settle_frames      = 0
still_counter      = 0
settle_ready_ctr   = 0

key_left = key_right = key_shift = False
hover_button = None

# ─── Main loop ────────────────────────────────────────────────────────────────

running = True
while running:
    # ── Event handling ────────────────────────────────────────────────────────
    mouse_pos    = pygame.mouse.get_pos()
    hover_button = next((n for n, r in buttons.items() if r.collidepoint(mouse_pos)), None)

    for event in pygame.event.get():

        if event.type == pygame.QUIT:
            running = False

        # ── Keyboard ──────────────────────────────────────────────────────────
        if event.type == pygame.KEYDOWN:

            if event.key == pygame.K_d:
                DEBUG = not DEBUG
            if event.key == pygame.K_m:
                sound_enabled = not sound_enabled
                (pygame.mixer.music.unpause if sound_enabled else pygame.mixer.music.pause)()

            if event.key == pygame.K_RETURN and game_over:
                reset_game()
                current_player    = 1
                game_over         = False
                winner            = None
                transition_active = False
                preview_active    = True
                preview_data      = _make_preview_data()
                preview_x         = SCREEN_WIDTH // 2
                preview_angle     = 0.0
                settling          = False
                dragging          = False
                continue

            if not game_over and preview_active and not settling and not transition_active:
                if event.key == pygame.K_LEFT:
                    key_left = True
                elif event.key == pygame.K_RIGHT:
                    key_right = True
                elif event.key in (pygame.K_LSHIFT, pygame.K_RSHIFT):
                    key_shift = True
                elif event.key == pygame.K_SPACE:
                    body = drop_tile(preview_data, preview_x, preview_y, preview_angle)
                    preview_active = False
                    settling       = True
                    settle_frames  = still_counter = settle_ready_ctr = 0

        if event.type == pygame.KEYUP:
            if event.key == pygame.K_LEFT:          key_left  = False
            elif event.key == pygame.K_RIGHT:       key_right = False
            elif event.key in (pygame.K_LSHIFT, pygame.K_RSHIFT): key_shift = False

        # ── Mouse ─────────────────────────────────────────────────────────────
        if event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
            if settling or transition_active or game_over:
                continue

            clicked_button = None
            for name, rect in buttons.items():
                if rect.collidepoint(event.pos):
                    clicked_button = name
                    break

            if clicked_button == "rotate":
                preview_angle += ANGLE_STEP
            elif clicked_button == "drop":
                body = drop_tile(preview_data, preview_x, preview_y, preview_angle)
                preview_active = False
                settling       = True
                settle_frames  = still_counter = settle_ready_ctr = 0
            elif preview_active and not settling:
                dragging  = True
                preview_x = event.pos[0]

        if event.type == pygame.MOUSEBUTTONUP and event.button == 1:
            dragging = False

        if event.type == pygame.MOUSEMOTION:
            if dragging and preview_active and not settling and not transition_active and not game_over:
                preview_x = event.pos[0]

    # ── Continuous key movement ───────────────────────────────────────────────
    if not game_over and preview_active and not settling and not transition_active:
        if key_left:   preview_x -= MOVE_STEP
        if key_right:  preview_x += MOVE_STEP
        if key_shift:  preview_angle += ANGLE_STEP

    preview_x = max(20, min(SCREEN_WIDTH - 20, preview_x))

    # ── Physics step (sub-stepped for stability) ──────────────────────────────
    for _ in range(8):
        space.step(1 / FPS / 8)

    # ── Camera scroll — only between turns, tracks settled pile ──────────────
    # Never update camera while a tile is in flight (prevents oscillation).
    if not settling:
        # Highest world-Y among all settled dynamic bodies
        settled_ys = [
            b.position.y
            for b in space.bodies
            if b.body_type == pymunk.Body.DYNAMIC
        ]
        if settled_ys:
            pile_peak_world = max(settled_ys)
            # We want pile_peak to appear at screen centre (SCREEN_HEIGHT // 2).
            # screen_y = SCREEN_HEIGHT - world_y + camera_y
            # Set screen_y = SCREEN_HEIGHT // 2:
            #   camera_target = world_y - SCREEN_HEIGHT + SCREEN_HEIGHT // 2
            #                 = world_y - SCREEN_HEIGHT // 2
            camera_target = max(0.0, pile_peak_world - SCREEN_HEIGHT // 2)
            camera_y += (camera_target - camera_y) * CAMERA_LERP_RATE

    # ── Settle detection ──────────────────────────────────────────────────────
    if settling:
        settle_frames += 1
        if all_bodies_still():
            still_counter += 1
        else:
            still_counter = settle_ready_ctr = 0

        resolved = False
        if still_counter >= STILL_FRAMES:
            settle_ready_ctr += 1
            if settle_ready_ctr >= SETTLE_READY_DELAY:
                resolved = True
        elif settle_frames >= SETTLE_DURATION:
            resolved = True

        if resolved:
            settling = False
            if check_loss(current_player):
                # Tile has fallen off bar — wait until it scrolls off screen
                watching_fall = True
            else:
                tiles_placed += 1
                if tiles_placed % LEVEL_TILES == 0:
                    current_level += 1
                    new_w = min(int(current_bar_width * BAR_GROWTH_FACTOR), MAX_BAR_WIDTH)
                    _rebuild_bar(new_w)
                    level_flash_timer = 120
                transition_active = True
                transition_timer  = 60
                next_player       = 2 if current_player == 1 else 1

    # ── Watch fallen tile leave screen before declaring game over ─────────────
    if watching_fall:
        if fallen_tile_off_screen(current_player):
            watching_fall = False
            game_over     = True
            winner        = 3 - current_player
            if sound_enabled and "game_over" in sounds:
                sounds["game_over"].play()

    # ── Player transition ─────────────────────────────────────────────────────
    if transition_active:
        transition_timer -= 1
        if transition_timer <= 0:
            transition_active = False
            current_player    = next_player
            preview_active    = True
            preview_data      = _make_preview_data()
            preview_x         = SCREEN_WIDTH // 2
            preview_angle     = 0.0
            dragging          = False
            key_left = key_right = key_shift = False

    # ── Drawing ───────────────────────────────────────────────────────────────
    active_p = next_player if transition_active else current_player
    draw_background(winner if game_over else active_p)

    # Bar — shadow first, then body, then highlight line on top edge
    bar_top_world  = bar_body.position.y + BAR_PHYSICS_HEIGHT / 2
    bar_top_screen = int(SCREEN_HEIGHT - bar_top_world + camera_y)
    bx = SCREEN_WIDTH // 2 - current_bar_width // 2

    # Drop shadow (3 px below, semi-transparent)
    shadow_surf = pygame.Surface((current_bar_width + 6, BAR_VISUAL_HEIGHT + 4), pygame.SRCALPHA)
    shadow_surf.fill((0, 0, 0, 60))
    screen.blit(shadow_surf, (bx - 3, bar_top_screen + 3))

    bar_rect = pygame.Rect(bx, bar_top_screen, current_bar_width, BAR_VISUAL_HEIGHT)
    pygame.draw.rect(screen, BAR_COLOR,   bar_rect, border_radius=4)
    pygame.draw.rect(screen, BAR_SHADOW,  bar_rect, 2, border_radius=4)
    # Highlight line — 1px bright strip at very top
    pygame.draw.line(screen, (180, 130, 70),
                     (bx + 6, bar_top_screen + 1),
                     (bx + current_bar_width - 6, bar_top_screen + 1), 1)

    # ── HUD panel (top-left) ─────────────────────────────────────────────────
    hud_panel = pygame.Surface((210, 92), pygame.SRCALPHA)
    pygame.draw.rect(hud_panel, (20, 20, 40, 160), (0, 0, 210, 92), border_radius=14)
    pygame.draw.rect(hud_panel, (255, 255, 255, 30), (0, 0, 210, 92), 1, border_radius=14)
    screen.blit(hud_panel, (10, 10))

    p_col  = P1_MAIN if active_p == 1 else P2_MAIN
    p_name = "Player 1" if active_p == 1 else "Player 2"
    hud_f1 = pygame.font.Font(None, 30)
    hud_f2 = pygame.font.Font(None, 24)

    # Player indicator dot + name
    pygame.draw.circle(screen, p_col, (30, 28), 8)
    screen.blit(hud_f1.render(p_name, True, (230, 235, 255)), (46, 20))

    # Level, tiles, countdown
    next_lvl = LEVEL_TILES - (tiles_placed % LEVEL_TILES)
    lines = [
        f"Level  {current_level}",
        f"Tiles  {tiles_placed}    Next lvl in {next_lvl}",
    ]
    for i, line in enumerate(lines):
        screen.blit(hud_f2.render(line, True, (190, 200, 230)), (18, 46 + i * 22))

    draw_objects()
    if DEBUG:
        draw_physics_outlines()

    # ── Drop guide — faint vertical dashed line under preview ────────────────
    if preview_active and not settling and not transition_active and not game_over:
        guide_surf = pygame.Surface((2, SCREEN_HEIGHT), pygame.SRCALPHA)
        for gy in range(0, SCREEN_HEIGHT, 14):
            pygame.draw.line(guide_surf, (120, 130, 160, 55), (0, gy), (0, gy + 7))
        screen.blit(guide_surf, (preview_x, 0))

    # ── Bottom toolbar background ─────────────────────────────────────────────
    toolbar_h = 70
    toolbar = pygame.Surface((SCREEN_WIDTH, toolbar_h), pygame.SRCALPHA)
    pygame.draw.rect(toolbar, (15, 15, 35, 200), (0, 0, SCREEN_WIDTH, toolbar_h))
    pygame.draw.line(toolbar, (255, 255, 255, 30), (0, 0), (SCREEN_WIDTH, 0), 1)
    screen.blit(toolbar, (0, SCREEN_HEIGHT - toolbar_h))

    # ── Buttons ───────────────────────────────────────────────────────────────
    for name, rect in buttons.items():
        main_c  = P1_MAIN  if active_p == 1 else P2_MAIN
        light_c = P1_LIGHT if active_p == 1 else P2_LIGHT
        dark_c  = P1_DARK  if active_p == 1 else P2_DARK
        disabled = settling or transition_active or game_over

        if disabled:
            fill = (80, 82, 95)
            border = (60, 62, 75)
        elif hover_button == name:
            fill = light_c
            border = dark_c
        else:
            fill = main_c
            border = dark_c

        draw_rounded_rect(screen, fill, rect, 12, border=2, border_color=border)
        label = btn_font.render(button_labels[name], True,
                                (200, 205, 215) if disabled else (255, 255, 255))
        screen.blit(label, label.get_rect(center=rect.center))

    # ── Preview tile ──────────────────────────────────────────────────────────
    if preview_active and not settling and not transition_active and not game_over:
        draw_preview(screen, preview_data, preview_x, preview_y, preview_angle, current_player)

    # ── Transition overlay ────────────────────────────────────────────────────
    if transition_active:
        # Full-screen dimmer
        ov = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
        ov.fill((0, 0, 0, 110))
        screen.blit(ov, (0, 0))

        p_color = P1_MAIN if next_player == 1 else P2_MAIN
        p_name  = "Player 1" if next_player == 1 else "Player 2"

        # Pill card
        card_w, card_h = 420, 130
        card_x = (SCREEN_WIDTH - card_w) // 2
        card_y = SCREEN_HEIGHT // 2 - card_h // 2
        card   = pygame.Surface((card_w, card_h), pygame.SRCALPHA)
        pygame.draw.rect(card, (*p_color, 220), (0, 0, card_w, card_h), border_radius=22)
        pygame.draw.rect(card, (255, 255, 255, 60), (0, 0, card_w, card_h), 2, border_radius=22)
        screen.blit(card, (card_x, card_y))

        f_big = pygame.font.Font(None, 62)
        f_sub = pygame.font.Font(None, 36)
        t1 = f_big.render(f"{p_name}'s Turn", True, (255, 255, 255))
        t2 = f_sub.render("Get Ready…", True, (255, 255, 255, 180))
        screen.blit(t1, t1.get_rect(center=(SCREEN_WIDTH // 2, card_y + 44)))
        screen.blit(t2, t2.get_rect(center=(SCREEN_WIDTH // 2, card_y + 95)))

    # ── Level-up flash banner ─────────────────────────────────────────────────
    if level_flash_timer > 0:
        level_flash_timer -= 1
        alpha = min(255, level_flash_timer * 5)
        lv_w, lv_h = 500, 110
        lv_surf = pygame.Surface((lv_w, lv_h), pygame.SRCALPHA)
        pygame.draw.rect(lv_surf, (20, 20, 20, int(alpha * 0.7)),
                         (0, 0, lv_w, lv_h), border_radius=18)
        pygame.draw.rect(lv_surf, (255, 215, 0, alpha),
                         (0, 0, lv_w, lv_h), 2, border_radius=18)
        fnt_big = pygame.font.Font(None, 78)
        fnt_sub = pygame.font.Font(None, 36)
        t1 = fnt_big.render(f"✦  LEVEL {current_level}  ✦", True, (255, 215, 0))
        t2 = fnt_sub.render(f"Bar width +20% → {current_bar_width}px", True, (200, 230, 255))
        t1.set_alpha(alpha); t2.set_alpha(alpha)
        lv_surf.blit(t1, t1.get_rect(centerx=lv_w//2, top=10))
        lv_surf.blit(t2, t2.get_rect(centerx=lv_w//2, top=72))
        screen.blit(lv_surf, ((SCREEN_WIDTH - lv_w) // 2, SCREEN_HEIGHT // 2 - 55))

    # ── Game-over overlay ─────────────────────────────────────────────────────
    if game_over:
        ov = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT), pygame.SRCALPHA)
        ov.fill((0, 0, 0, 160))
        screen.blit(ov, (0, 0))

        w_color = P1_MAIN if winner == 1 else P2_MAIN
        w_name  = "Player 1" if winner == 1 else "Player 2"

        card_w, card_h = 460, 160
        card_x = (SCREEN_WIDTH - card_w) // 2
        card_y = SCREEN_HEIGHT // 2 - card_h // 2
        card   = pygame.Surface((card_w, card_h), pygame.SRCALPHA)
        pygame.draw.rect(card, (*w_color, 230), (0, 0, card_w, card_h), border_radius=24)
        pygame.draw.rect(card, (255, 255, 255, 80), (0, 0, card_w, card_h), 2, border_radius=24)
        # Gold shimmer line
        pygame.draw.line(card, (255, 215, 0, 180), (30, 8), (card_w - 30, 8), 2)
        screen.blit(card, (card_x, card_y))

        f_big = pygame.font.Font(None, 76)
        f_sub = pygame.font.Font(None, 38)
        f_tip = pygame.font.Font(None, 30)
        t1 = f_big.render(f"🏆  {w_name} Wins!", True, (255, 255, 255))
        t2 = f_sub.render(f"Tiles stacked: {tiles_placed}", True, (255, 255, 255, 210))
        t3 = f_tip.render("Press ENTER to play again", True, (220, 230, 255, 180))
        screen.blit(t1, t1.get_rect(center=(SCREEN_WIDTH // 2, card_y + 50)))
        screen.blit(t2, t2.get_rect(center=(SCREEN_WIDTH // 2, card_y + 100)))
        screen.blit(t3, t3.get_rect(center=(SCREEN_WIDTH // 2, card_y + 135)))

    pygame.display.flip()
    clock.tick(FPS)

pygame.quit()
sys.exit()
